"""Shared, dialect-agnostic rendering loop.

Walks the schema once and delegates every dialect-specific decision
(type spelling, auto-increment PKs, quoting, FK placement) to a `Dialect`.
"""

from collections import defaultdict

from app.schemas.schema_models import SchemaResponse

from .dialects import Dialect


def _valid_relationships(schema: SchemaResponse):
    names = {t.name for t in schema.tables}
    return [
        rel
        for rel in schema.relationships
        if rel.source_table in names and rel.target_table in names
    ]


def _create_table(table, dialect: Dialect, inline_fks) -> str:
    columns = table.columns or []
    table_q = dialect.quote(table.name)

    if not columns:
        # Every supported dialect rejects a table with no columns.
        return f'-- table "{table.name}" skipped: it has no columns'

    pk_columns = [c for c in columns if c.primary_key]
    sole_pk = pk_columns[0].name if len(pk_columns) == 1 else None

    lines: list[str] = []
    for column in columns:
        column_q = dialect.quote(column.name)
        if column.name == sole_pk:
            lines.append(dialect.primary_key_column(column_q, column.type))
        else:
            lines.append(f"{column_q} {dialect.column_type(column.type)}")

    if len(pk_columns) > 1:
        cols = ", ".join(dialect.quote(c.name) for c in pk_columns)
        lines.append(f"PRIMARY KEY ({cols})")

    if inline_fks is not None:
        for rel in inline_fks.get(table.name, []):
            lines.append(
                f"FOREIGN KEY ({dialect.quote(rel.source_column)}) "
                f"REFERENCES {dialect.quote(rel.target_table)} "
                f"({dialect.quote(rel.target_column)})"
            )

    body = ",\n".join(f"    {line}" for line in lines)
    return f"CREATE TABLE {table_q} (\n{body}\n);"


def _alter_add_fk(rel, dialect: Dialect) -> str:
    constraint = dialect.quote(f"fk_{rel.source_table}_{rel.source_column}")
    return (
        f"ALTER TABLE {dialect.quote(rel.source_table)}\n"
        f"    ADD CONSTRAINT {constraint}\n"
        f"    FOREIGN KEY ({dialect.quote(rel.source_column)}) "
        f"REFERENCES {dialect.quote(rel.target_table)} "
        f"({dialect.quote(rel.target_column)});"
    )


def render_sql(schema: SchemaResponse, dialect: Dialect) -> str:
    project = schema.project_name or "database"
    parts: list[str] = [
        f"-- {dialect.label} schema for {project}",
        "-- Generated by SchemaForge AI (deterministic, no AI)",
    ]

    relationships = _valid_relationships(schema)

    fks_by_table = defaultdict(list)
    if dialect.inline_foreign_keys:
        for rel in relationships:
            fks_by_table[rel.source_table].append(rel)

    creates = [
        _create_table(
            table,
            dialect,
            inline_fks=fks_by_table if dialect.inline_foreign_keys else None,
        )
        for table in schema.tables
    ]
    if creates:
        parts.append("")
        parts.append("\n\n".join(creates))

    if not dialect.inline_foreign_keys and relationships:
        parts.append("")
        parts.append("-- Foreign keys")
        parts.append("\n\n".join(_alter_add_fk(rel, dialect) for rel in relationships))

    return "\n".join(parts).rstrip() + "\n"
