"""Deterministic SQL generation from a validated schema.

No AI. Given a `SchemaResponse`, this produces PostgreSQL DDL:
CREATE TABLE statements, primary keys, and foreign keys derived from the
relationships list. The same schema always yields byte-identical SQL.

Only PostgreSQL is supported for now.
"""

import re

from app.schemas.schema_models import SchemaResponse

_IDENTIFIER_RE = re.compile(r"^[a-z_][a-z0-9_]*$")

# Integer types that become auto-incrementing when they are a sole primary key.
_SERIAL_MAP = {
    "smallint": "SMALLSERIAL",
    "int2": "SMALLSERIAL",
    "integer": "SERIAL",
    "int": "SERIAL",
    "int4": "SERIAL",
    "bigint": "BIGSERIAL",
    "int8": "BIGSERIAL",
}


def _quote_identifier(name: str) -> str:
    if _IDENTIFIER_RE.match(name):
        return name
    # Escape embedded double quotes, then wrap.
    return '"' + name.replace('"', '""') + '"'


def _format_type(raw_type: str) -> str:
    return " ".join(raw_type.strip().split()).upper()


def _column_definition(column, *, is_sole_primary_key: bool) -> str:
    name = _quote_identifier(column.name)
    normalised = " ".join(column.type.strip().lower().split())

    if is_sole_primary_key and normalised in _SERIAL_MAP:
        return f"{name} {_SERIAL_MAP[normalised]} PRIMARY KEY"

    type_sql = _format_type(column.type)
    if is_sole_primary_key:
        return f"{name} {type_sql} PRIMARY KEY"
    return f"{name} {type_sql}"


def _create_table_statement(table) -> str:
    columns = table.columns or []
    table_name = _quote_identifier(table.name)

    if not columns:
        return f"CREATE TABLE {table_name} ();"

    pk_columns = [c for c in columns if c.primary_key]
    sole_pk = pk_columns[0].name if len(pk_columns) == 1 else None

    lines = [
        _column_definition(column, is_sole_primary_key=(column.name == sole_pk))
        for column in columns
    ]

    # Composite primary key -> table-level constraint.
    if len(pk_columns) > 1:
        cols = ", ".join(_quote_identifier(c.name) for c in pk_columns)
        lines.append(f"PRIMARY KEY ({cols})")

    body = ",\n".join(f"    {line}" for line in lines)
    return f"CREATE TABLE {table_name} (\n{body}\n);"


def _foreign_key_statements(schema: SchemaResponse) -> list[str]:
    table_names = {t.name for t in schema.tables}
    statements: list[str] = []

    for rel in schema.relationships:
        if rel.source_table not in table_names or rel.target_table not in table_names:
            continue

        constraint = _quote_identifier(
            f"fk_{rel.source_table}_{rel.source_column}"
        )
        statements.append(
            f"ALTER TABLE {_quote_identifier(rel.source_table)}\n"
            f"    ADD CONSTRAINT {constraint}\n"
            f"    FOREIGN KEY ({_quote_identifier(rel.source_column)}) "
            f"REFERENCES {_quote_identifier(rel.target_table)} "
            f"({_quote_identifier(rel.target_column)});"
        )

    return statements


def generate_postgres_sql(schema: SchemaResponse) -> str:
    """Return PostgreSQL DDL for the given schema."""
    project = schema.project_name or "database"

    parts: list[str] = [
        f"-- PostgreSQL schema for {project}",
        "-- Generated by SchemaForge AI (deterministic, no AI)",
    ]

    create_statements = [
        _create_table_statement(table) for table in schema.tables
    ]
    if create_statements:
        parts.append("")
        parts.append("\n\n".join(create_statements))

    fk_statements = _foreign_key_statements(schema)
    if fk_statements:
        parts.append("")
        parts.append("-- Foreign keys")
        parts.append("\n\n".join(fk_statements))

    return "\n".join(parts).rstrip() + "\n"
